"""
anomaly_detector.py
--------------------
Two anomaly detection strategies for turbine sensor time series data:

1. Rolling Z-Score (primary / explainable method)
   For each point, computes how many standard deviations it is from the
   recent rolling mean. Flags a point as anomalous if it crosses a
   threshold. This is simple, fast, works well for a single sensor,
   and -- importantly -- is easy to explain fully in an interview.

2. Isolation Forest (stretch / multivariate method)
   An unsupervised ML model that isolates points that are "few and
   different" across all sensors jointly. Useful for catching
   anomalies that only appear when combinations of sensors move
   together in an unusual way (e.g. temperature and vibration both
   rising slightly -- not extreme enough individually to trip a
   z-score threshold, but abnormal as a combination).
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest


def detect_anomalies_zscore(series: pd.Series, window: int = 15, threshold: float = 2.0):
    """
    Flags points whose rolling z-score exceeds `threshold`, PLUS a
    "stuck sensor" check for flatline stretches (a real-world failure
    mode a pure z-score can miss, since a perfectly flat signal has
    zero local variance and therefore a z-score of 0).

    Parameters
    ----------
    series : pd.Series
        The sensor readings.
    window : int
        Rolling window size (number of readings) used to compute the
        local mean/std. Using a rolling window (rather than the whole
        series) lets the detector adapt to slow, legitimate drift.
    threshold : float
        Number of standard deviations away from the rolling mean that
        counts as anomalous. 2.5-3.0 is a common statistical convention.

    Returns
    -------
    pd.Series of bool, same index as input, True where anomalous.
    pd.Series of float, the z-score at each point (useful for plotting).
    """
    # NOTE: stats are computed on the *trailing* window (shifted by one
    # point) rather than a centered/inclusive window. If the current point
    # were included in its own mean/std, a genuine spike would inflate the
    # very std used to judge it -- "self-masking" -- and quietly hide itself.
    # Using only prior history keeps the detector responsive to sudden changes.
    trailing = series.shift(1)
    rolling_mean = trailing.rolling(window=window, min_periods=window // 2).mean()
    rolling_std = trailing.rolling(window=window, min_periods=window // 2).std()

    # baseline "typical" noise level for this sensor, used to detect stuck sensors
    baseline_std = rolling_std.median()

    # avoid divide-by-zero during flatline/stuck-sensor stretches
    rolling_std_safe = rolling_std.replace(0, np.nan)

    z_scores = (series - rolling_mean) / rolling_std_safe
    z_scores = z_scores.fillna(0)

    is_spike_or_drift = z_scores.abs() > threshold

    # a rolling std that collapses to near-zero relative to this sensor's
    # normal noise level means the reading has "stuck" (stopped changing) -
    # a classic instrumentation fault, not caught by z-score alone
    is_stuck = (rolling_std < 0.1 * baseline_std) & rolling_std.notna()

    is_anomaly = is_spike_or_drift | is_stuck
    return is_anomaly, z_scores


def detect_anomalies_isolation_forest(df: pd.DataFrame, sensor_columns, contamination: float = 0.03):
    """
    Fits an Isolation Forest jointly across multiple sensor columns and
    flags rows that look anomalous as a combination of readings.

    Parameters
    ----------
    df : pd.DataFrame
        Must contain the columns listed in `sensor_columns`.
    sensor_columns : list[str]
        Which sensor columns to consider jointly.
    contamination : float
        Expected proportion of anomalies in the dataset (model hyper-parameter).

    Returns
    -------
    pd.Series of bool, True where the model flags the row as anomalous.
    """
    X = df[sensor_columns].ffill().bfill()

    model = IsolationForest(
        n_estimators=200,
        contamination=contamination,
        random_state=42,
    )
    predictions = model.fit_predict(X)  # -1 = anomaly, 1 = normal
    is_anomaly = pd.Series(predictions == -1, index=df.index)
    return is_anomaly


def evaluate_detection(true_labels: pd.Series, predicted_labels: pd.Series):
    """
    Quick precision/recall/F1 against the ground-truth anomaly labels
    generated by the simulator. Useful to quote a number on your resume
    / in an interview (e.g. "achieved 0.82 F1 on simulated anomalies").
    """
    tp = int((true_labels & predicted_labels).sum())
    fp = int((~true_labels & predicted_labels).sum())
    fn = int((true_labels & ~predicted_labels).sum())

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) > 0 else 0.0

    return {"precision": round(precision, 3), "recall": round(recall, 3), "f1": round(f1, 3)}
